### ISSUE TITLE
Mistaken BlockInstance Interface

### ISSUE THREAD

**Issue by jaonoctus** [mempool/mempool-js#3]
## Description

I can't use `getBlocks` function without parameters.

## Steps to reproduce

```ts
import mempoolJS from '@mempool/mempool-js'

const { blocks } = mempoolJS()

// Error `Expected 1 arguments, but got 0.`
blocks.getBlocks().then(console.log).catch(console.error)

// works
blocks.getBlocks({}).then(console.log).catch(console.error)
```

## Possible fix

https://github.com/mempool/mempool-js/blob/f39361263a16d234988bf58175fd3f5e192ecc87/src/interfaces.ts#L57

Should be:

```ts
 getBlocks: (params?: { start_height: number }) => Promise<Block>;
 ```

**Comment by MiguelMedeiros** [comment]
@jaonoctus Thank a lot for the report! 👍

I've sent this [PR](https://github.com/mempool/mempool-js/pull/5) to fix this bug.
Would you mind to review it for me? 😄
